on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      #          cache: "yarn"
      - run: npm install
      - run: yarn build
      - run: pm2 delete goemergo-api-dev
      - run: pm2 start yarn --name "goemergo-api-dev" -- run start:dev
